### ISSUE TITLE
Qwen-VL-Plus, Ferret

### ISSUE THREAD

**Issue by fnauman** [SkalskiP/awesome-foundation-and-multimodal-models#4]
Thanks for a great list. 

Two suggestions:

1. Qwen-VL-Plus: You have listed Qwen-VL, which has an updated version Qwen-VL-Plus that looks much better than its predecessor:
Demo: https://huggingface.co/spaces/Qwen/Qwen-VL-Plus
Code: https://github.com/QwenLM/Qwen-VL#qwen-vl-plus

2. Ferret by Apple: 
Paper: https://arxiv.org/abs/2310.07704
Code: https://github.com/apple/ml-ferret

**Comment by SkalskiP** [comment]
I agree! Would you like to create a PR and add those?
