### ISSUE TITLE
Having model repositories

### ISSUE THREAD

**Issue by merveenoyan** [SkalskiP/awesome-foundation-and-multimodal-models#8]
Hiya 👋  I think it would be nice to link to HF model repositories next to Space ones given GH repositories are often used to host the code, and they have limitations on the file size the users can upload so weights are often hosted on HF Hub. Moreover, model repositories are better for hosting models - the model cards are often written by the model authors, linked to the dataset the model was trained on etc.
What do you think?

**Comment by SkalskiP** [comment]
Hi @merveenoyan! 👋🏻 Let's do it! Will you help me out?

**Comment by merveenoyan** [comment]
@SkalskiP sure I can open a PR 😊

**Comment by SkalskiP** [comment]
@merveenoyan awesome, we would need to add new column to [`data.csv`](https://github.com/SkalskiP/awesome-foundation-and-multimodal-models/blob/master/automation/data.csv).

**Comment by merveenoyan** [comment]
@SkalskiP just opened the PR
